services:
  frontend:
    image: ghcr.io/derrick-nuby/quantix:prod
    container_name: quantix-frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://derrickuser:123@database:5432/QuantixDBV2?schema=public"
      environment: "production"
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - app-network

  database:
    container_name: quantix-database
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: derrickuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: QuantixDBV2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
